version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80
  backend:
    build: ./backend
    ports:
      - 5000:5000
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: edtech123
    volumes:
      - /home/dudeful/coding/docker/edtech/data/mongo:/data/db
